#!/bin/sh

VERSION="0.0.1"

base="https://ustvgo.tv/"

selection=$(curl -s "$base"|sed 's_<li>_\n_g'|sed -nE 's_.*a href="([^"]*)">([^<]*) <.*_\1\t\2_p'|
fzf --with-nth 2.. --reverse --header "Select a channel to watch" --height=40% --border)
title=$(printf "%s" "$selection"|cut -f2)

url=$(printf "%s" "$selection"|cut -f1)

echo URL = $url

#iframe=$(curl -s "$url"|sed -nE "s_.*iframe src='([^']*)'.*_\1_p")
iframe="player.php?stream=ESPN2"
echo iframe = $iframe

hls_link=$(curl -s -e "$url" "$base$iframe"|sed -nE "s@.*hls_src='([^']*)'.*@\1@p")

[ -z "$hls_link" ] && echo "No HLS link found" && exit 1

#echo $hls_link

mpv --force-media-title="$title" "$hls_link"
